/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'id' : bigint,
  'code' : string,
  'name' : string,
  'createdAt' : bigint,
  'isActive' : boolean,
  'accountType' : AccountType,
  'normalBalance' : NormalBalance,
}
export type AccountType = { 'Aset' : null } |
  { 'Beban' : null } |
  { 'Modal' : null } |
  { 'Pendapatan' : null } |
  { 'Kewajiban' : null };
export interface BalanceSheet {
  'totalModal' : bigint,
  'totalAset' : bigint,
  'details' : Array<BalanceSheetDetail>,
  'totalKewajiban' : bigint,
}
export interface BalanceSheetDetail { 'account' : Account, 'amount' : bigint }
export interface GeneralLedger {
  'entries' : Array<LedgerEntry>,
  'account' : Account,
}
export interface IncomeStatement {
  'labaRugi' : bigint,
  'totalPendapatan' : bigint,
  'details' : Array<IncomeStatementDetail>,
  'totalBeban' : bigint,
}
export interface IncomeStatementDetail {
  'account' : Account,
  'amount' : bigint,
}
export interface JournalEntry {
  'id' : bigint,
  'date' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'reference' : string,
  'description' : string,
  'lines' : Array<JournalLine>,
  'periodId' : bigint,
}
export interface JournalLine {
  'accountId' : bigint,
  'description' : string,
  'kredit' : bigint,
  'debit' : bigint,
}
export interface LedgerEntry {
  'balance' : bigint,
  'date' : string,
  'reference' : string,
  'description' : string,
  'kredit' : bigint,
  'debit' : bigint,
}
export interface LocalUser {
  'username' : string,
  'createdAt' : bigint,
  'role' : UserRole,
  'isActive' : boolean,
  'passwordHash' : string,
}
export type NormalBalance = { 'Debit' : null } |
  { 'Kredit' : null };
export interface Period {
  'id' : bigint,
  'status' : PeriodStatus,
  'month' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'year' : bigint,
}
export type PeriodStatus = { 'Open' : null } |
  { 'Closed' : null };
export type Result = { 'ok' : null } |
  { 'err' : string };
export interface TrialBalanceEntry {
  'totalKredit' : bigint,
  'account' : Account,
  'totalDebit' : bigint,
}
export interface UserEntry { 'principal' : Principal, 'role' : UserRole }
export interface UserProfile { 'name' : string }
export type UserRole = { 'manager' : null } |
  { 'admin' : null } |
  { 'bendahara' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAccount' : ActorMethod<
    [string, string, AccountType, NormalBalance],
    Account
  >,
  'addJournalEntry' : ActorMethod<
    [string, string, string, bigint, Array<JournalLine>],
    JournalEntry
  >,
  'addPeriod' : ActorMethod<[string, bigint, bigint], Period>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'assignCustomRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changeLocalPassword' : ActorMethod<[string, string], boolean>,
  'closePeriod' : ActorMethod<[bigint], Period>,
  'createLocalUser' : ActorMethod<[string, string, UserRole], Result>,
  'deleteJournalEntry' : ActorMethod<[bigint], boolean>,
  'deleteLocalUser' : ActorMethod<[string], boolean>,
  'getAccountById' : ActorMethod<[bigint], [] | [Account]>,
  'getAccounts' : ActorMethod<[], Array<Account>>,
  'getBalanceSheet' : ActorMethod<[[] | [bigint]], BalanceSheet>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getGeneralLedger' : ActorMethod<[bigint, [] | [bigint]], GeneralLedger>,
  'getIncomeStatement' : ActorMethod<[[] | [bigint]], IncomeStatement>,
  'getJournalEntries' : ActorMethod<[[] | [bigint]], Array<JournalEntry>>,
  'getJournalEntryById' : ActorMethod<[bigint], [] | [JournalEntry]>,
  'getLogoUrl' : ActorMethod<[], [] | [string]>,
  'getPeriods' : ActorMethod<[], Array<Period>>,
  'getSessionRole' : ActorMethod<[string], [] | [UserRole]>,
  'getTrialBalance' : ActorMethod<[[] | [bigint]], Array<TrialBalanceEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUsersList' : ActorMethod<[], Array<UserEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listLocalUsers' : ActorMethod<[], Array<LocalUser>>,
  'loginLocal' : ActorMethod<[string, string], [] | [string]>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedData' : ActorMethod<[], undefined>,
  'setLogoUrl' : ActorMethod<[string], undefined>,
  'updateAccount' : ActorMethod<[bigint, string, string, boolean], Account>,
  'updateJournalEntry' : ActorMethod<
    [bigint, string, string, string, Array<JournalLine>],
    JournalEntry
  >,
  'validateSessionToken' : ActorMethod<[string], [] | [string]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];