/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AccountType = IDL.Variant({
  'Aset' : IDL.Null,
  'Beban' : IDL.Null,
  'Modal' : IDL.Null,
  'Pendapatan' : IDL.Null,
  'Kewajiban' : IDL.Null,
});
export const NormalBalance = IDL.Variant({
  'Debit' : IDL.Null,
  'Kredit' : IDL.Null,
});
export const Account = IDL.Record({
  'id' : IDL.Nat,
  'code' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'accountType' : AccountType,
  'normalBalance' : NormalBalance,
});
export const JournalLine = IDL.Record({
  'accountId' : IDL.Nat,
  'description' : IDL.Text,
  'kredit' : IDL.Nat,
  'debit' : IDL.Nat,
});
export const JournalEntry = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'reference' : IDL.Text,
  'description' : IDL.Text,
  'lines' : IDL.Vec(JournalLine),
  'periodId' : IDL.Nat,
});
export const PeriodStatus = IDL.Variant({
  'Open' : IDL.Null,
  'Closed' : IDL.Null,
});
export const Period = IDL.Record({
  'id' : IDL.Nat,
  'status' : PeriodStatus,
  'month' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'year' : IDL.Nat,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'manager' : IDL.Null,
  'admin' : IDL.Null,
  'bendahara' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const BalanceSheetDetail = IDL.Record({
  'account' : Account,
  'amount' : IDL.Nat,
});
export const BalanceSheet = IDL.Record({
  'totalModal' : IDL.Nat,
  'totalAset' : IDL.Nat,
  'details' : IDL.Vec(BalanceSheetDetail),
  'totalKewajiban' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const LedgerEntry = IDL.Record({
  'balance' : IDL.Int,
  'date' : IDL.Text,
  'reference' : IDL.Text,
  'description' : IDL.Text,
  'kredit' : IDL.Nat,
  'debit' : IDL.Nat,
});
export const GeneralLedger = IDL.Record({
  'entries' : IDL.Vec(LedgerEntry),
  'account' : Account,
});
export const IncomeStatementDetail = IDL.Record({
  'account' : Account,
  'amount' : IDL.Nat,
});
export const IncomeStatement = IDL.Record({
  'labaRugi' : IDL.Int,
  'totalPendapatan' : IDL.Nat,
  'details' : IDL.Vec(IncomeStatementDetail),
  'totalBeban' : IDL.Nat,
});
export const TrialBalanceEntry = IDL.Record({
  'totalKredit' : IDL.Nat,
  'account' : Account,
  'totalDebit' : IDL.Nat,
});
export const UserEntry = IDL.Record({
  'principal' : IDL.Principal,
  'role' : UserRole,
});
export const LocalUser = IDL.Record({
  'username' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : UserRole,
  'isActive' : IDL.Bool,
  'passwordHash' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAccount' : IDL.Func(
      [IDL.Text, IDL.Text, AccountType, NormalBalance],
      [Account],
      [],
    ),
  'addJournalEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(JournalLine)],
      [JournalEntry],
      [],
    ),
  'addPeriod' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [Period], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'assignCustomRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changeLocalPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'closePeriod' : IDL.Func([IDL.Nat], [Period], []),
  'createLocalUser' : IDL.Func([IDL.Text, IDL.Text, UserRole], [Result], []),
  'deleteJournalEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteLocalUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAccountById' : IDL.Func([IDL.Nat], [IDL.Opt(Account)], ['query']),
  'getAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
  'getBalanceSheet' : IDL.Func([IDL.Opt(IDL.Nat)], [BalanceSheet], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getGeneralLedger' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Nat)],
      [GeneralLedger],
      ['query'],
    ),
  'getIncomeStatement' : IDL.Func(
      [IDL.Opt(IDL.Nat)],
      [IncomeStatement],
      ['query'],
    ),
  'getJournalEntries' : IDL.Func(
      [IDL.Opt(IDL.Nat)],
      [IDL.Vec(JournalEntry)],
      ['query'],
    ),
  'getJournalEntryById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(JournalEntry)],
      ['query'],
    ),
  'getLogoUrl' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getPeriods' : IDL.Func([], [IDL.Vec(Period)], ['query']),
  'getSessionRole' : IDL.Func([IDL.Text], [IDL.Opt(UserRole)], ['query']),
  'getTrialBalance' : IDL.Func(
      [IDL.Opt(IDL.Nat)],
      [IDL.Vec(TrialBalanceEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsersList' : IDL.Func([], [IDL.Vec(UserEntry)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listLocalUsers' : IDL.Func([], [IDL.Vec(LocalUser)], ['query']),
  'loginLocal' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedData' : IDL.Func([], [], []),
  'setLogoUrl' : IDL.Func([IDL.Text], [], []),
  'updateAccount' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Bool],
      [Account],
      [],
    ),
  'updateJournalEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(JournalLine)],
      [JournalEntry],
      [],
    ),
  'validateSessionToken' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AccountType = IDL.Variant({
    'Aset' : IDL.Null,
    'Beban' : IDL.Null,
    'Modal' : IDL.Null,
    'Pendapatan' : IDL.Null,
    'Kewajiban' : IDL.Null,
  });
  const NormalBalance = IDL.Variant({
    'Debit' : IDL.Null,
    'Kredit' : IDL.Null,
  });
  const Account = IDL.Record({
    'id' : IDL.Nat,
    'code' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'accountType' : AccountType,
    'normalBalance' : NormalBalance,
  });
  const JournalLine = IDL.Record({
    'accountId' : IDL.Nat,
    'description' : IDL.Text,
    'kredit' : IDL.Nat,
    'debit' : IDL.Nat,
  });
  const JournalEntry = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'reference' : IDL.Text,
    'description' : IDL.Text,
    'lines' : IDL.Vec(JournalLine),
    'periodId' : IDL.Nat,
  });
  const PeriodStatus = IDL.Variant({ 'Open' : IDL.Null, 'Closed' : IDL.Null });
  const Period = IDL.Record({
    'id' : IDL.Nat,
    'status' : PeriodStatus,
    'month' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'year' : IDL.Nat,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'manager' : IDL.Null,
    'admin' : IDL.Null,
    'bendahara' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const BalanceSheetDetail = IDL.Record({
    'account' : Account,
    'amount' : IDL.Nat,
  });
  const BalanceSheet = IDL.Record({
    'totalModal' : IDL.Nat,
    'totalAset' : IDL.Nat,
    'details' : IDL.Vec(BalanceSheetDetail),
    'totalKewajiban' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const LedgerEntry = IDL.Record({
    'balance' : IDL.Int,
    'date' : IDL.Text,
    'reference' : IDL.Text,
    'description' : IDL.Text,
    'kredit' : IDL.Nat,
    'debit' : IDL.Nat,
  });
  const GeneralLedger = IDL.Record({
    'entries' : IDL.Vec(LedgerEntry),
    'account' : Account,
  });
  const IncomeStatementDetail = IDL.Record({
    'account' : Account,
    'amount' : IDL.Nat,
  });
  const IncomeStatement = IDL.Record({
    'labaRugi' : IDL.Int,
    'totalPendapatan' : IDL.Nat,
    'details' : IDL.Vec(IncomeStatementDetail),
    'totalBeban' : IDL.Nat,
  });
  const TrialBalanceEntry = IDL.Record({
    'totalKredit' : IDL.Nat,
    'account' : Account,
    'totalDebit' : IDL.Nat,
  });
  const UserEntry = IDL.Record({
    'principal' : IDL.Principal,
    'role' : UserRole,
  });
  const LocalUser = IDL.Record({
    'username' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : UserRole,
    'isActive' : IDL.Bool,
    'passwordHash' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAccount' : IDL.Func(
        [IDL.Text, IDL.Text, AccountType, NormalBalance],
        [Account],
        [],
      ),
    'addJournalEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(JournalLine)],
        [JournalEntry],
        [],
      ),
    'addPeriod' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [Period], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'assignCustomRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changeLocalPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'closePeriod' : IDL.Func([IDL.Nat], [Period], []),
    'createLocalUser' : IDL.Func([IDL.Text, IDL.Text, UserRole], [Result], []),
    'deleteJournalEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteLocalUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAccountById' : IDL.Func([IDL.Nat], [IDL.Opt(Account)], ['query']),
    'getAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
    'getBalanceSheet' : IDL.Func([IDL.Opt(IDL.Nat)], [BalanceSheet], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getGeneralLedger' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Nat)],
        [GeneralLedger],
        ['query'],
      ),
    'getIncomeStatement' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IncomeStatement],
        ['query'],
      ),
    'getJournalEntries' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IDL.Vec(JournalEntry)],
        ['query'],
      ),
    'getJournalEntryById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(JournalEntry)],
        ['query'],
      ),
    'getLogoUrl' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getPeriods' : IDL.Func([], [IDL.Vec(Period)], ['query']),
    'getSessionRole' : IDL.Func([IDL.Text], [IDL.Opt(UserRole)], ['query']),
    'getTrialBalance' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IDL.Vec(TrialBalanceEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsersList' : IDL.Func([], [IDL.Vec(UserEntry)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listLocalUsers' : IDL.Func([], [IDL.Vec(LocalUser)], ['query']),
    'loginLocal' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedData' : IDL.Func([], [], []),
    'setLogoUrl' : IDL.Func([IDL.Text], [], []),
    'updateAccount' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Bool],
        [Account],
        [],
      ),
    'updateJournalEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(JournalLine)],
        [JournalEntry],
        [],
      ),
    'validateSessionToken' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };