/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface IncomeStatement {
    labaRugi: bigint;
    totalPendapatan: bigint;
    details: Array<IncomeStatementDetail>;
    totalBeban: bigint;
}
export interface GeneralLedger {
    entries: Array<LedgerEntry>;
    account: Account;
}
export interface Account {
    id: bigint;
    code: string;
    name: string;
    createdAt: bigint;
    isActive: boolean;
    accountType: AccountType;
    normalBalance: NormalBalance;
}
export interface JournalLine {
    accountId: bigint;
    description: string;
    kredit: bigint;
    debit: bigint;
}
export interface LedgerEntry {
    balance: bigint;
    date: string;
    reference: string;
    description: string;
    kredit: bigint;
    debit: bigint;
}
export interface BalanceSheetDetail {
    account: Account;
    amount: bigint;
}
export interface TrialBalanceEntry {
    totalKredit: bigint;
    account: Account;
    totalDebit: bigint;
}
export interface Period {
    id: bigint;
    status: PeriodStatus;
    month: bigint;
    name: string;
    createdAt: bigint;
    year: bigint;
}
export interface UserEntry {
    principal: Principal;
    role: UserRole;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface LocalUser {
    username: string;
    createdAt: bigint;
    role: UserRole;
    isActive: boolean;
    passwordHash: string;
}
export interface JournalEntry {
    id: bigint;
    date: string;
    createdAt: bigint;
    createdBy: Principal;
    reference: string;
    description: string;
    lines: Array<JournalLine>;
    periodId: bigint;
}
export interface IncomeStatementDetail {
    account: Account;
    amount: bigint;
}
export interface BalanceSheet {
    totalModal: bigint;
    totalAset: bigint;
    details: Array<BalanceSheetDetail>;
    totalKewajiban: bigint;
}
export interface UserProfile {
    name: string;
}
export enum AccountType {
    Aset = "Aset",
    Beban = "Beban",
    Modal = "Modal",
    Pendapatan = "Pendapatan",
    Kewajiban = "Kewajiban"
}
export enum NormalBalance {
    Debit = "Debit",
    Kredit = "Kredit"
}
export enum PeriodStatus {
    Open = "Open",
    Closed = "Closed"
}
export enum UserRole {
    manager = "manager",
    admin = "admin",
    bendahara = "bendahara",
    user = "user",
    guest = "guest"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAccount(code: string, name: string, accountType: AccountType, normalBalance: NormalBalance): Promise<Account>;
    addJournalEntry(date: string, description: string, reference: string, periodId: bigint, lines: Array<JournalLine>): Promise<JournalEntry>;
    addPeriod(name: string, month: bigint, year: bigint): Promise<Period>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    assignCustomRole(user: Principal, role: UserRole): Promise<void>;
    changeLocalPassword(username: string, newPasswordHash: string): Promise<boolean>;
    closePeriod(id: bigint): Promise<Period>;
    createLocalUser(username: string, passwordHash: string, role: UserRole): Promise<Result>;
    deleteJournalEntry(id: bigint): Promise<boolean>;
    deleteLocalUser(username: string): Promise<boolean>;
    getAccountById(id: bigint): Promise<Account | null>;
    getAccounts(): Promise<Array<Account>>;
    getBalanceSheet(periodId: bigint | null): Promise<BalanceSheet>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getGeneralLedger(accountId: bigint, periodId: bigint | null): Promise<GeneralLedger>;
    getIncomeStatement(periodId: bigint | null): Promise<IncomeStatement>;
    getJournalEntries(periodId: bigint | null): Promise<Array<JournalEntry>>;
    getJournalEntryById(id: bigint): Promise<JournalEntry | null>;
    getLogoUrl(): Promise<string | null>;
    getPeriods(): Promise<Array<Period>>;
    getSessionRole(token: string): Promise<UserRole | null>;
    getTrialBalance(periodId: bigint | null): Promise<Array<TrialBalanceEntry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUsersList(): Promise<Array<UserEntry>>;
    isCallerAdmin(): Promise<boolean>;
    listLocalUsers(): Promise<Array<LocalUser>>;
    loginLocal(username: string, passwordHash: string): Promise<string | null>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seedData(): Promise<void>;
    setLogoUrl(url: string): Promise<void>;
    updateAccount(id: bigint, code: string, name: string, isActive: boolean): Promise<Account>;
    updateJournalEntry(id: bigint, date: string, description: string, reference: string, lines: Array<JournalLine>): Promise<JournalEntry>;
    validateSessionToken(token: string): Promise<string | null>;
}
import type { Account as _Account, AccountType as _AccountType, BalanceSheet as _BalanceSheet, BalanceSheetDetail as _BalanceSheetDetail, GeneralLedger as _GeneralLedger, IncomeStatement as _IncomeStatement, IncomeStatementDetail as _IncomeStatementDetail, JournalEntry as _JournalEntry, LedgerEntry as _LedgerEntry, LocalUser as _LocalUser, NormalBalance as _NormalBalance, Period as _Period, PeriodStatus as _PeriodStatus, Result as _Result, TrialBalanceEntry as _TrialBalanceEntry, UserEntry as _UserEntry, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAccount(arg0: string, arg1: string, arg2: AccountType, arg3: NormalBalance): Promise<Account> {
        if (this.processError) {
            try {
                const result = await this.actor.addAccount(arg0, arg1, to_candid_AccountType_n1(this._uploadFile, this._downloadFile, arg2), to_candid_NormalBalance_n3(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Account_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAccount(arg0, arg1, to_candid_AccountType_n1(this._uploadFile, this._downloadFile, arg2), to_candid_NormalBalance_n3(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Account_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async addJournalEntry(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: Array<JournalLine>): Promise<JournalEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.addJournalEntry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJournalEntry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addPeriod(arg0: string, arg1: bigint, arg2: bigint): Promise<Period> {
        if (this.processError) {
            try {
                const result = await this.actor.addPeriod(arg0, arg1, arg2);
                return from_candid_Period_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPeriod(arg0, arg1, arg2);
            return from_candid_Period_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCustomRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCustomRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCustomRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async changeLocalPassword(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.changeLocalPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeLocalPassword(arg0, arg1);
            return result;
        }
    }
    async closePeriod(arg0: bigint): Promise<Period> {
        if (this.processError) {
            try {
                const result = await this.actor.closePeriod(arg0);
                return from_candid_Period_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closePeriod(arg0);
            return from_candid_Period_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async createLocalUser(arg0: string, arg1: string, arg2: UserRole): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.createLocalUser(arg0, arg1, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLocalUser(arg0, arg1, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteJournalEntry(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJournalEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJournalEntry(arg0);
            return result;
        }
    }
    async deleteLocalUser(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLocalUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLocalUser(arg0);
            return result;
        }
    }
    async getAccountById(arg0: bigint): Promise<Account | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccountById(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccountById(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAccounts(): Promise<Array<Account>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccounts();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccounts();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBalanceSheet(arg0: bigint | null): Promise<BalanceSheet> {
        if (this.processError) {
            try {
                const result = await this.actor.getBalanceSheet(to_candid_opt_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_BalanceSheet_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBalanceSheet(to_candid_opt_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_BalanceSheet_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGeneralLedger(arg0: bigint, arg1: bigint | null): Promise<GeneralLedger> {
        if (this.processError) {
            try {
                const result = await this.actor.getGeneralLedger(arg0, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg1));
                return from_candid_GeneralLedger_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGeneralLedger(arg0, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg1));
            return from_candid_GeneralLedger_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIncomeStatement(arg0: bigint | null): Promise<IncomeStatement> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncomeStatement(to_candid_opt_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_IncomeStatement_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncomeStatement(to_candid_opt_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_IncomeStatement_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJournalEntries(arg0: bigint | null): Promise<Array<JournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJournalEntries(to_candid_opt_n23(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJournalEntries(to_candid_opt_n23(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getJournalEntryById(arg0: bigint): Promise<JournalEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJournalEntryById(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJournalEntryById(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLogoUrl(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogoUrl();
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogoUrl();
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPeriods(): Promise<Array<Period>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPeriods();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPeriods();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionRole(arg0: string): Promise<UserRole | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionRole(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionRole(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrialBalance(arg0: bigint | null): Promise<Array<TrialBalanceEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrialBalance(to_candid_opt_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrialBalance(to_candid_opt_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsersList(): Promise<Array<UserEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsersList();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsersList();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listLocalUsers(): Promise<Array<LocalUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLocalUsers();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLocalUsers();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginLocal(arg0: string, arg1: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loginLocal(arg0, arg1);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginLocal(arg0, arg1);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async seedData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedData();
            return result;
        }
    }
    async setLogoUrl(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLogoUrl(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLogoUrl(arg0);
            return result;
        }
    }
    async updateAccount(arg0: bigint, arg1: string, arg2: string, arg3: boolean): Promise<Account> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAccount(arg0, arg1, arg2, arg3);
                return from_candid_Account_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAccount(arg0, arg1, arg2, arg3);
            return from_candid_Account_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateJournalEntry(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: Array<JournalLine>): Promise<JournalEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJournalEntry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJournalEntry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async validateSessionToken(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.validateSessionToken(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateSessionToken(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AccountType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccountType): AccountType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Account_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Account): Account {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_BalanceSheetDetail_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BalanceSheetDetail): BalanceSheetDetail {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_BalanceSheet_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BalanceSheet): BalanceSheet {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_GeneralLedger_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GeneralLedger): GeneralLedger {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_IncomeStatementDetail_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncomeStatementDetail): IncomeStatementDetail {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_IncomeStatement_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncomeStatement): IncomeStatement {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_LocalUser_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LocalUser): LocalUser {
    return from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_NormalBalance_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NormalBalance): NormalBalance {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_PeriodStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PeriodStatus): PeriodStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Period_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Period): Period {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_TrialBalanceEntry_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrialBalanceEntry): TrialBalanceEntry {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_UserEntry_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserEntry): UserEntry {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Account]): Account | null {
    return value.length === 0 ? null : from_candid_Account_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JournalEntry]): JournalEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserRole]): UserRole | null {
    return value.length === 0 ? null : from_candid_UserRole_n42(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PeriodStatus;
    month: bigint;
    name: string;
    createdAt: bigint;
    year: bigint;
}): {
    id: bigint;
    status: PeriodStatus;
    month: bigint;
    name: string;
    createdAt: bigint;
    year: bigint;
} {
    return {
        id: value.id,
        status: from_candid_PeriodStatus_n13(_uploadFile, _downloadFile, value.status),
        month: value.month,
        name: value.name,
        createdAt: value.createdAt,
        year: value.year
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalModal: bigint;
    totalAset: bigint;
    details: Array<_BalanceSheetDetail>;
    totalKewajiban: bigint;
}): {
    totalModal: bigint;
    totalAset: bigint;
    details: Array<BalanceSheetDetail>;
    totalKewajiban: bigint;
} {
    return {
        totalModal: value.totalModal,
        totalAset: value.totalAset,
        details: from_candid_vec_n26(_uploadFile, _downloadFile, value.details),
        totalKewajiban: value.totalKewajiban
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    account: _Account;
    amount: bigint;
}): {
    account: Account;
    amount: bigint;
} {
    return {
        account: from_candid_Account_n5(_uploadFile, _downloadFile, value.account),
        amount: value.amount
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entries: Array<_LedgerEntry>;
    account: _Account;
}): {
    entries: Array<LedgerEntry>;
    account: Account;
} {
    return {
        entries: value.entries,
        account: from_candid_Account_n5(_uploadFile, _downloadFile, value.account)
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    labaRugi: bigint;
    totalPendapatan: bigint;
    details: Array<_IncomeStatementDetail>;
    totalBeban: bigint;
}): {
    labaRugi: bigint;
    totalPendapatan: bigint;
    details: Array<IncomeStatementDetail>;
    totalBeban: bigint;
} {
    return {
        labaRugi: value.labaRugi,
        totalPendapatan: value.totalPendapatan,
        details: from_candid_vec_n36(_uploadFile, _downloadFile, value.details),
        totalBeban: value.totalBeban
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalKredit: bigint;
    account: _Account;
    totalDebit: bigint;
}): {
    totalKredit: bigint;
    account: Account;
    totalDebit: bigint;
} {
    return {
        totalKredit: value.totalKredit,
        account: from_candid_Account_n5(_uploadFile, _downloadFile, value.account),
        totalDebit: value.totalDebit
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    role: _UserRole;
}): {
    principal: Principal;
    role: UserRole;
} {
    return {
        principal: value.principal,
        role: from_candid_UserRole_n42(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    createdAt: bigint;
    role: _UserRole;
    isActive: boolean;
    passwordHash: string;
}): {
    username: string;
    createdAt: bigint;
    role: UserRole;
    isActive: boolean;
    passwordHash: string;
} {
    return {
        username: value.username,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n42(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive,
        passwordHash: value.passwordHash
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    code: string;
    name: string;
    createdAt: bigint;
    isActive: boolean;
    accountType: _AccountType;
    normalBalance: _NormalBalance;
}): {
    id: bigint;
    code: string;
    name: string;
    createdAt: bigint;
    isActive: boolean;
    accountType: AccountType;
    normalBalance: NormalBalance;
} {
    return {
        id: value.id,
        code: value.code,
        name: value.name,
        createdAt: value.createdAt,
        isActive: value.isActive,
        accountType: from_candid_AccountType_n7(_uploadFile, _downloadFile, value.accountType),
        normalBalance: from_candid_NormalBalance_n9(_uploadFile, _downloadFile, value.normalBalance)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Debit: null;
} | {
    Kredit: null;
}): NormalBalance {
    return "Debit" in value ? NormalBalance.Debit : "Kredit" in value ? NormalBalance.Kredit : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Open: null;
} | {
    Closed: null;
}): PeriodStatus {
    return "Open" in value ? PeriodStatus.Open : "Closed" in value ? PeriodStatus.Closed : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manager: null;
} | {
    admin: null;
} | {
    bendahara: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "manager" in value ? UserRole.manager : "admin" in value ? UserRole.admin : "bendahara" in value ? UserRole.bendahara : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Aset: null;
} | {
    Beban: null;
} | {
    Modal: null;
} | {
    Pendapatan: null;
} | {
    Kewajiban: null;
}): AccountType {
    return "Aset" in value ? AccountType.Aset : "Beban" in value ? AccountType.Beban : "Modal" in value ? AccountType.Modal : "Pendapatan" in value ? AccountType.Pendapatan : "Kewajiban" in value ? AccountType.Kewajiban : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Account>): Array<Account> {
    return value.map((x)=>from_candid_Account_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BalanceSheetDetail>): Array<BalanceSheetDetail> {
    return value.map((x)=>from_candid_BalanceSheetDetail_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IncomeStatementDetail>): Array<IncomeStatementDetail> {
    return value.map((x)=>from_candid_IncomeStatementDetail_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Period>): Array<Period> {
    return value.map((x)=>from_candid_Period_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TrialBalanceEntry>): Array<TrialBalanceEntry> {
    return value.map((x)=>from_candid_TrialBalanceEntry_n45(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserEntry>): Array<UserEntry> {
    return value.map((x)=>from_candid_UserEntry_n48(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LocalUser>): Array<LocalUser> {
    return value.map((x)=>from_candid_LocalUser_n51(_uploadFile, _downloadFile, x));
}
function to_candid_AccountType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountType): _AccountType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_NormalBalance_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NormalBalance): _NormalBalance {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    manager: null;
} | {
    admin: null;
} | {
    bendahara: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.manager ? {
        manager: null
    } : value == UserRole.admin ? {
        admin: null
    } : value == UserRole.bendahara ? {
        bendahara: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountType): {
    Aset: null;
} | {
    Beban: null;
} | {
    Modal: null;
} | {
    Pendapatan: null;
} | {
    Kewajiban: null;
} {
    return value == AccountType.Aset ? {
        Aset: null
    } : value == AccountType.Beban ? {
        Beban: null
    } : value == AccountType.Modal ? {
        Modal: null
    } : value == AccountType.Pendapatan ? {
        Pendapatan: null
    } : value == AccountType.Kewajiban ? {
        Kewajiban: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NormalBalance): {
    Debit: null;
} | {
    Kredit: null;
} {
    return value == NormalBalance.Debit ? {
        Debit: null
    } : value == NormalBalance.Kredit ? {
        Kredit: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
